-- Step 1: Create Tables
CREATE TABLE DEPT (
    DEPTNO INT PRIMARY KEY,
    DNAME VARCHAR(20) UNIQUE,
    LOCATION VARCHAR(50) NOT NULL
);

CREATE TABLE EMPLOYEES (
    EMPNO INT PRIMARY KEY,
    ENAME VARCHAR(50) NOT NULL,
    JOB VARCHAR(20) NOT NULL,
    MGR INT NOT NULL,
    HIREDATE DATE,
    SALARY DECIMAL(6,2) DEFAULT 4000.00,
    DEPTNO INT,
    FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)
);

-- Step 2: Insert into DEPT first
INSERT INTO DEPT (DEPTNO, DNAME, LOCATION)
VALUES 
(10, 'HR', 'New York'),
(20, 'IT', 'San Francisco'),
(30, 'Admin', 'Chicago');

-- Step 3: Then insert into EMPLOYEES
INSERT INTO EMPLOYEES (EMPNO, ENAME, JOB, MGR, HIREDATE, SALARY, DEPTNO)
VALUES (1001, 'Alice', 'Manager', 0, '2020-01-15', 6000.00, 10);

INSERT INTO EMPLOYEES (EMPNO, ENAME, JOB, MGR, HIREDATE, SALARY, DEPTNO)
VALUES (1002, 'Bob', 'Developer', 1001, '2021-03-22', 4500.00, 20);

INSERT INTO EMPLOYEES (EMPNO, ENAME, JOB, MGR, HIREDATE, SALARY, DEPTNO)
VALUES (1003, 'Charlie', 'Analyst', 1001, '2021-06-10', 5000.00, 30);

INSERT INTO EMPLOYEES (EMPNO, ENAME, JOB, MGR, HIREDATE, SALARY, DEPTNO)
VALUES (1004, 'Diana', 'Clerk', 1003, '2022-09-01', 3500.00, 30);

INSERT INTO EMPLOYEES (EMPNO, ENAME, JOB, MGR, HIREDATE, SALARY, DEPTNO)
VALUES (1005, 'Ethan', 'Support', 1002, '2023-02-14', 4000.00, 20);




--INNER JOIN

SELECT E.EMPNO, E.ENAME, E.JOB, D.DNAME, D.LOCATION
FROM EMPLOYEES E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

--LEFT JOIN

SELECT E.EMPNO, E.ENAME, E.DEPTNO, D.DNAME
FROM EMPLOYEES E
LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

--RIGHT JOIN

SELECT E.EMPNO, E.ENAME, E.DEPTNO, D.DNAME
FROM EMPLOYEES E
RIGHT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

--FULL OUTER JOIN (MySQL doesn’t support)

SELECT E.EMPNO, E.ENAME, E.DEPTNO, D.DNAME
FROM EMPLOYEES E
LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO
UNION
SELECT E.EMPNO, E.ENAME, E.DEPTNO, D.DNAME
FROM EMPLOYEES E
RIGHT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

